"""geadm — read-only troubleshooting / debug / stats CLI for Google Gemini Enterprise.

Targets the Discovery Engine / Agentspace product (discoveryengine.googleapis.com).
Strictly read-only: needs only roles/discoveryengine.viewer, roles/logging.viewer
and roles/monitoring.viewer. Auth is Application Default Credentials.
"""

from __future__ import annotations

from dataclasses import dataclass

import typer

app = typer.Typer(
    name="geadm",
    help="CLI for Google Gemini Enterprise.",
    no_args_is_help=True,
    rich_markup_mode="rich",
)


@dataclass
class AppState:
    project: str | None
    location: str
    quota_project: str | None = None


@app.callback()
def main(
    ctx: typer.Context,
    project: str = typer.Option(
        None,
        "--project",
        "-p",
        help="GCP project ID (defaults to the ADC project).",
        envvar="GOOGLE_CLOUD_PROJECT",
    ),
    location: str = typer.Option(
        "global",
        "--location",
        "-l",
        help="Gemini Enterprise location (e.g. global, us, eu).",
    ),
    quota_project: str = typer.Option(
        None,
        "--quota-project",
        help=(
            "Project to bill API quota against (defaults to --project). Useful "
            "when you lack serviceusage.services.use on the target project."
        ),
        envvar="GOOGLE_CLOUD_QUOTA_PROJECT",
    ),
) -> None:
    """CLI for Google Gemini Enterprise."""
    ctx.obj = AppState(project=project, location=location, quota_project=quota_project)


# ---- command groups (implemented in geadm/commands/) -----------------------

from geadm.commands import doctor as doctor_cmd  # noqa: E402
from geadm.commands import armor as armor_cmd  # noqa: E402
from geadm.commands import info as info_cmd  # noqa: E402
from geadm.commands import logs as logs_cmd  # noqa: E402
from geadm.commands import ls as ls_cmd  # noqa: E402
from geadm.commands import stats as stats_cmd  # noqa: E402

app.add_typer(ls_cmd.app, name="ls")
app.add_typer(logs_cmd.app, name="logs")
app.command(name="stats")(stats_cmd.stats_command)
app.command(name="quota")(stats_cmd.quota_command)
app.command(name="doctor")(doctor_cmd.doctor_command)
app.command(name="info")(info_cmd.info_command)
app.command(name="armor")(armor_cmd.armor_command)


def _build_commit() -> str:
    """Commit baked in at build time, or live git in a dev checkout."""
    try:
        from geadm._build import COMMIT  # generated by hatch_build.py

        return COMMIT
    except ImportError:
        pass
    try:
        import subprocess
        from pathlib import Path

        return (
            subprocess.run(
                ["git", "rev-parse", "--short=7", "HEAD"],
                capture_output=True,
                text=True,
                cwd=Path(__file__).resolve().parent,
                timeout=5,
            ).stdout.strip()
            or "unknown"
        )
    except Exception:
        return "unknown"


@app.command()
def version(
    as_json: bool = typer.Option(False, "--json", help="Emit machine-readable JSON."),
) -> None:
    """Show version and build commit."""
    from importlib.metadata import PackageNotFoundError
    from importlib.metadata import version as pkg_version

    try:
        release = pkg_version("geadm")
    except PackageNotFoundError:
        from geadm import __version__ as release

    data = {"version": release, "tag": f"v{release}", "commit": _build_commit()}
    if as_json:
        from geadm.render import emit_json

        emit_json(data)
    else:
        print(f"geadm {data['version']} ({data['tag']}, commit {data['commit']})")


def _installed_version() -> str:
    from importlib.metadata import PackageNotFoundError
    from importlib.metadata import version as pkg_version

    try:
        return pkg_version("geadm")
    except PackageNotFoundError:
        from geadm import __version__

        return __version__


def _latest_version(timeout: float = 5.0) -> str | None:
    """Latest geadm version on PyPI, or None if the check fails (offline etc.)."""
    import json
    import urllib.request

    try:
        with urllib.request.urlopen(
            "https://pypi.org/pypi/geadm/json", timeout=timeout
        ) as resp:
            return json.load(resp)["info"]["version"]
    except Exception:
        return None


def _install_method() -> tuple[str, list[str] | None]:
    """Detect how geadm was installed and the command to upgrade it.

    Returns (label, argv-or-None). None means we can't upgrade automatically.
    """
    import sys

    prefix = sys.prefix.replace("\\", "/")
    # --no-cache forces a fresh index fetch: right after a release the PyPI
    # index a cached client sees can lag, and update would silently no-op.
    if "/pipx/venvs/" in prefix:
        return "pipx", ["pipx", "upgrade", "geadm", "--pip-args=--no-cache-dir"]
    if "/uv/tools/" in prefix or "/uv/tools" in prefix:
        return "uv tool", ["uv", "tool", "upgrade", "--no-cache", "geadm"]
    return "pip", [
        sys.executable, "-m", "pip", "install", "--upgrade", "--no-cache-dir", "geadm"
    ]


def _version_tuple(v: str) -> tuple:
    parts = []
    for chunk in v.split("."):
        num = "".join(c for c in chunk if c.isdigit())
        parts.append(int(num) if num else 0)
    return tuple(parts)


@app.command()
def update(
    check: bool = typer.Option(
        False, "--check", help="Only report whether an update is available."
    ),
    as_json: bool = typer.Option(False, "--json", help="Emit machine-readable JSON."),
) -> None:
    """Update geadm to the latest release."""
    import subprocess

    from geadm.render import console, emit_json, err_console

    current = _installed_version()
    latest = _latest_version()
    method, argv = _install_method()
    outdated = latest is not None and _version_tuple(latest) > _version_tuple(current)

    if as_json:
        emit_json(
            {
                "current": current,
                "latest": latest,
                "outdated": outdated,
                "install_method": method,
            }
        )
        return

    if latest is None:
        err_console.print("[yellow]Could not reach PyPI to check for updates.[/yellow]")
        raise typer.Exit(code=1)
    if not outdated:
        console.print(f"geadm is up to date ([bold]{current}[/bold]).")
        return

    console.print(f"Update available: [bold]{current}[/bold] → [bold green]{latest}[/bold green]")
    if check:
        console.print(f"Run [bold]geadm update[/bold] (or `{' '.join(argv)}`).")
        return
    if argv is None:
        console.print("Upgrade geadm with your package manager.")
        return

    console.print(f"[dim]$ {' '.join(argv)}[/dim]")
    try:
        subprocess.run(argv, check=True)
    except FileNotFoundError:
        err_console.print(
            f"[yellow]{argv[0]} not found on PATH.[/yellow] Upgrade manually: "
            f"{' '.join(argv)}"
        )
        raise typer.Exit(code=1) from None
    except subprocess.CalledProcessError as exc:
        err_console.print(f"[red]Upgrade failed[/red] (exit {exc.returncode}).")
        raise typer.Exit(code=exc.returncode) from None


def run() -> None:
    """Console entrypoint: run the app with concise permission-error reporting."""
    import warnings

    from google.api_core.exceptions import PermissionDenied
    from requests import HTTPError

    from geadm.render import err_console

    # google.auth warns that user ADC has no quota project; geadm sets one
    # itself (see auth.Clients._credentials), so the warning is just noise.
    warnings.filterwarnings(
        "ignore",
        message=".*end user credentials.*without a quota project.*",
        category=UserWarning,
    )
    # The API can return enum values newer than the published client knows
    # (e.g. preview ContentConfig values); geadm renders them numerically.
    warnings.filterwarnings(
        "ignore",
        message=r"Unrecognized \w+ enum value.*",
        category=UserWarning,
    )

    try:
        app()
    except KeyboardInterrupt:
        raise SystemExit(130) from None
    except PermissionDenied as exc:
        message = (getattr(exc, "message", None) or str(exc)).splitlines()[0]
        err_console.print(f"[bold red]Permission denied:[/bold red] {message}")
        if "serviceusage" in message or "USER_PROJECT_DENIED" in str(exc.errors):
            err_console.print(
                "[yellow]Hint:[/yellow] your ADC user credentials must bill API "
                "quota to a project where you hold serviceusage.services.use. "
                "Pass [bold]--quota-project <project>[/bold] (or set "
                "GOOGLE_CLOUD_QUOTA_PROJECT) to bill a project you can use."
            )
        else:
            err_console.print(
                "[yellow]Hint:[/yellow] geadm needs roles/discoveryengine.viewer, "
                "roles/logging.viewer and roles/monitoring.viewer on the target "
                "project."
            )
        raise SystemExit(1) from None
    except HTTPError as exc:
        response = exc.response
        err_console.print(f"[bold red]API error:[/bold red] {exc}")
        if response is not None and response.status_code == 403:
            err_console.print(
                "[yellow]Hint:[/yellow] check roles/discoveryengine.viewer on the "
                "target project, or --quota-project if the error mentions quota."
            )
        raise SystemExit(1) from None


if __name__ == "__main__":
    run()
