"""Build hook: bake the git commit into getop/_build.py at package build time.

Installed packages have no .git directory, so `getop version` reads the
commit from this generated module. Resolution order: GITHUB_SHA (CI builds),
`git rev-parse` (local builds), then whatever an sdist already carries (the
wheel-from-sdist step has neither git nor CI env).
"""

import os
import subprocess

from hatchling.builders.hooks.plugin.interface import BuildHookInterface

_TEMPLATE = '''"""Build metadata generated by hatch_build.py — do not edit."""

COMMIT = "{commit}"
'''


def _resolve_commit(root: str) -> str:
    commit = os.environ.get("GITHUB_SHA", "")[:7]
    if commit:
        return commit
    try:
        return subprocess.run(
            ["git", "rev-parse", "--short=7", "HEAD"],
            capture_output=True,
            text=True,
            cwd=root,
            timeout=5,
        ).stdout.strip()
    except Exception:
        return ""


class BuildInfoHook(BuildHookInterface):
    def initialize(self, version: str, build_data: dict) -> None:
        path = os.path.join(self.root, "getop", "_build.py")
        commit = _resolve_commit(self.root)
        # Building a wheel from an sdist has neither git nor CI env: keep
        # the value the sdist build baked in.
        if commit or not os.path.exists(path):
            with open(path, "w") as f:
                f.write(_TEMPLATE.format(commit=commit or "unknown"))
        # The file is gitignored (generated), so hatchling's VCS-based file
        # selection skips it; force it into the artifact explicitly.
        build_data.setdefault("force_include", {})[path] = "getop/_build.py"
